/** All player-facing bilingual strings, kept in one place. */
export const COPY = {
  brand: {
    titleAr: 'لعبة أحمد ولؤي',
    titleEn: 'AHMAD & LUAY',
    subtitleEn: 'KINGDOM SHIFT',
    subtitleAr: 'بوابة المملكة',
  },
  menu: {
    startAr: 'ابدأ الرحلة',
    startEn: 'ENTER THE KINGDOM',
    controlsAr: 'التحكم والإعدادات',
    controlsEn: 'CONTROLS & SETTINGS',
    taglineAr: 'بين المدينة والصحراء... حافظ على استقرار البوابة.',
    taglineEn: 'BETWEEN CITY AND DESERT... KEEP THE GATE STABLE.',
    bestAr: 'أفضل نتيجة',
    bestEn: 'BEST RUN',
  },
  intro: {
    beats: [
      { ar: 'بوابة المملكة جاهزة', en: 'KINGDOM GATE ONLINE' },
      { ar: 'بدّل بين الواقعين', en: 'SHIFT BETWEEN REALITIES' },
    ],
    skip: 'Space / Enter to skip',
  },
  loading: {
    stages: ['معايرة شبكة البوابة', 'ربط النواة الكمّية', 'بانتظار اتصال البوابة'],
    stagesEn: ['CALIBRATING GATE LATTICE', 'BINDING QUANTUM CORE', 'GATE LINK PENDING'],
  },
  hud: {
    scoreAr: 'النتيجة',
    scoreEn: 'SCORE',
    distanceAr: 'المسافة',
    distanceEn: 'DISTANCE',
    energyAr: 'الطاقة',
    energyEn: 'ENERGY',
    speedEn: 'VELOCITY',
    speedAr: 'السرعة',
    comboAr: 'تتابع',
    overdriveReadyAr: 'الاندفاع جاهز',
    overdriveReadyEn: 'OVERDRIVE READY — SHIFT',
    overdriveActiveAr: 'الاندفاع نشط',
    overdriveActiveEn: 'OVERDRIVE ACTIVE',
  },
  pause: {
    titleAr: 'البوابة متوقفة',
    titleEn: 'GATE SUSPENDED',
    resumeAr: 'متابعة',
    resumeEn: 'RESUME',
    restartAr: 'إعادة',
    restartEn: 'RESTART',
    quitAr: 'إنهاء الرحلة',
    quitEn: 'ABANDON RUN',
  },
  gameover: {
    titleAr: 'انهيار البوابة',
    titleEn: 'THE GATE COLLAPSED',
    restartAr: 'العودة إلى البوابة',
    restartEn: 'RE-ENTER THE GATE',
    menuAr: 'القائمة الرئيسية',
    menuEn: 'MAIN MENU',
    finalAr: 'النتيجة النهائية',
    finalEn: 'FINAL SCORE',
    bestAr: 'الأفضل',
    bestEn: 'BEST',
    newBestEn: 'NEW BEST',
    distanceAr: 'المسافة',
    distanceEn: 'DISTANCE',
    timeAr: 'مدة الصمود',
    timeEn: 'SURVIVAL',
    comboAr: 'أعلى تتابع',
    comboEn: 'HIGHEST COMBO',
    shardsAr: 'البلورات',
    shardsEn: 'SHARDS',
    hintEn: 'PRESS R TO RE-ENTER',
  },
  popups: {
    nearMiss: [
      { ar: 'نجاة', en: 'NEAR MISS' },
      { ar: 'مراوغة', en: 'GATE DODGE' },
      { ar: 'بالكاد', en: 'CLOSE CALL' },
    ],
    phase: [
      { ar: 'عبور مثالي', en: 'PERFECT PHASE' },
      { ar: 'انزلاق البوابة', en: 'GATE SLIP' },
    ],
    overdrive: { ar: 'اندفاع', en: 'OVERDRIVE' },
    collapse: { ar: 'انهيار البوابة', en: 'GATE COLLAPSE' },
  },
  hints: [
    { ar: 'تحرّك للتوجيه', en: 'MOVE TO STEER' },
    { ar: 'مسافة للتبديل', en: 'SPACE TO SHIFT REALITY' },
    { ar: 'اجمع البلورات', en: 'COLLECT SHARDS' },
    { ar: 'شفت لتفعيل الاندفاع', en: 'SHIFT ACTIVATES OVERDRIVE' },
  ],
  controls: {
    headingEn: 'PROTOCOL // CONTROLS',
    headingAr: 'التحكم',
    settingsHeadingEn: 'SYSTEMS // SETTINGS',
    settingsHeadingAr: 'الإعدادات',
    closeAr: 'إغلاق',
    closeEn: 'CLOSE',
    rows: [
      { ar: 'التوجيه', en: 'Steer', keys: ['W A S D', '← ↑ ↓ →', 'MOUSE'] },
      { ar: 'تبديل الواقع', en: 'Shift reality', keys: ['SPACE'] },
      { ar: 'الاندفاع', en: 'Overdrive (meter full)', keys: ['SHIFT'] },
      { ar: 'إيقاف مؤقت', en: 'Pause / resume', keys: ['P', 'ESC'] },
      { ar: 'إعادة المحاولة', en: 'Restart (after collapse)', keys: ['R'] },
      { ar: 'تخطي المقدمة', en: 'Skip intro', keys: ['SPACE', 'ENTER'] },
    ],
    settings: [
      { key: 'sound', ar: 'المؤثرات الصوتية', en: 'Sound effects' },
      { key: 'music', ar: 'الأجواء الصوتية', en: 'Ambience' },
      { key: 'volume', ar: 'مستوى الصوت', en: 'Master volume' },
      { key: 'quality', ar: 'جودة الرسوم', en: 'Graphics' },
      { key: 'reducedMotion', ar: 'تقليل الحركة', en: 'Reduced motion' },
      { key: 'highContrast', ar: 'تباين عالٍ', en: 'High contrast UI' },
      { key: 'tutorial', ar: 'إرشادات اللعب', en: 'Tutorial hints' },
    ],
    replayAr: 'إعادة',
    replayEn: 'Replay',
  },
} as const
